:smtp_settings:
  :address: smtp.gmail.com
  :domain: gmail.com
  :port: 587
  :authentication: :login
  :user_name: agiles2012-notifications@agiles.org
  :password: 179l5s2011    
:host: agiles-call4papers.heroku.com
:conference_name: √Ågiles 2012
:speaker_promotion_code: SPK8729277
